### ISSUE TITLE
启动程序报错A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by zqclair** [blogwy/BilibiliVideoDownload#31]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: listen EACCES: permission denied 0.0.0.0:8964
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.listen (D:\Program Files\BilibiliVideoDownload\resources\app.asar\node_modules\express\lib\application.js:618:24)
    at App.<anonymous> (D:\Program Files\BilibiliVideoDownload\resources\app.asar\background.js:1:305719)
    at App.emit (events.js:223:5)

一启动程序就这个错误，请问有没有解决方案？

**Comment by blogwy** [comment]
我关注一下

**Comment by blogwy** [comment]
看错误好像是端口监听没有权限导致的，软件需要监听8964端口，作为图片代理服务。windows第一次打开软件时候，应该会有防火墙提示一个弹窗，要点击允许，可能你禁止了，或者是其他原因导致端口占用或者禁止。

**Comment by zqclair** [comment]
ok,搞定了，谢谢~

**Comment by archerx3** [comment]
@blogwy M1 Mac上发生这个如何解决?

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot create a string longer than 0x1fffffe8 characters
at Object.slice (buffer.js:608:37)
at Buffer.toString (buffer.js:805:14)
at Object.readFileSync (fs.js:421:41)
at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
at ElectronStore.get store [as store] (/Applications/BilibiliVideoDownload.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:276:29)
at new Conf (/Applications/BilibiliVideoDownload.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
at new ElectronStore (/Applications/BilibiliVideoDownload.app/Contents/Resources/app.asar/node_modules/electron-store/index.js:69:3)
at Module.<anonymous> (/Applications/BilibiliVideoDownload.app/Contents/Resources/app.asar/background.js:1:306038)
at r (/Applications/BilibiliVideoDownload.app/Contents/Resources/app.asar/background.js:1:110)
at Object.<anonymous> (/Applications/
```
