### ISSUE TITLE
TypeError: Cannot read property 'quality' of undefined

### ISSUE THREAD

**Issue by chn-lee-yumi** [blogwy/BilibiliVideoDownload#7]
➜  BilibiliVideoDownload git:(master) ✗ node app.js
请输入av号...av50596322
这是个单P视频
(node:71797) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'quality' of undefined
    at Object.getQuality (/Users/liyumin/Files/BilibiliVideoDownload/utils/getUrl.js:47:46)
    at async main (/Users/liyumin/Files/BilibiliVideoDownload/app.js:20:16)
(node:71797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chn-lee-yumi** [comment]
发现原因了，不应该加av两个字。建议在文档里面写清楚一下。
